version: '3'
services:
  bot:
    build: .
    expose:
      - 5050
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
  db:
    image: mongo
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
